# Generated by Django 4.1.3 on 2022-11-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passwords',
            new_name='Password',
        ),
    ]
